<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>
<body>
<h1>Detail Employee</h1>


<h3>Name : <?= $result['name'] ?></h3>
<h3>Email : <?= $result['email'] ?></h3>
<h3>Phone : <?= $result['phone'] ?></h3>
<h3>Address : <?= $result['address'] ?></h3>
<h3>Position : <?= $result['position'] ?></h3>
<h3>Salary : <?= $result['salary'] ?></h3>
<h3>Skills : <?php foreach ($result['skills'] as $list): ?>
            <?= $list['skill'] ?>,
    <?php endforeach; ?></h3>

</body>
</html>
